version: '3.3'
services:
    db:
        image: postgres:14.1-alpine
        restart: always
        ports:
          - '5432:5432'
        volumes: 
          - .postgres-data:/var/lib/postgresql/data/
          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
          - ./sql/data/:/docker-entrypoint-initdb.d/data/
        env_file:
          - 'app-pokemon-damage-calculator/variables.env'
    api:
        build: .
        volumes:
          - .:/code
        ports:
          - '8000:8000'
        env_file:
          - 'app-pokemon-damage-calculator/variables.env'
        links:
          - db
        command: uvicorn app-pokemon-damage-calculator.app.main:app --host 0.0.0.0
